In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import spacy

In [5]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

In [6]:
from sklearn.metrics import confusion_matrix

In [7]:
from sklearn.naive_bayes import MultinomialNB

In [12]:
columns = pd.read_csv('/Users/djbetts/Desktop/Capstone2/2019_build/raw_2019.csv',low_memory=False, index_col='Unnamed: 0')

In [13]:
columns.columns

Index(['abstract', 'web_url', 'snippet', 'lead_paragraph', 'print_section',
       'print_page', 'source', 'multimedia', 'headline', 'keywords',
       'pub_date', 'document_type', 'news_desk', 'section_name', 'byline',
       'type_of_material', '_id', 'word_count', 'uri', 'subsection_name',
       'text'],
      dtype='object')

In [14]:
XY_columns = ['type_of_material','text']

In [ ]:
df = pd.read_csv('/Users/djbetts/Desktop/archive/corpus.csv', low_memory=False, usecols=XY_columns)


In [1]:
def vectorize_type(df):
    y_vectorize_df = df.copy
    y_vectorize_df['type_of_material'].replace({'Op-Ed': 1,
                                       'News': 0}, inplace=True)
    return y_vectorize_df

In [11]:
type(type_text_df.text[0])

list

In [12]:
type_text_df.type_of_material.replace({'Op-Ed': 1,
                                       'News': 0}, inplace=True)

In [13]:
type_text_df

type_of_material                                               text
0                    1  ['From, the, Treaty, of, Versailles, to, Prohi...
1                    1  ['Imagine, what, we, could, do, with, our, mon...
2                    1  ['Can, the, Constitution, withstand, the, part...
3                    1  ['The, Christian, right, doesn’t, like, the, p...
4                    1  ['The, United, States, is, spending, beyond, i...
...                ...                                                ...
3469                 0  ['By, Margaret, Lyons',, 'No, matter, how, muc...
3470                 0  ['On, Politics, With, Lisa, Lerer',, 'By, Lisa...
3471                 0  ['transcript',, '“There’s, not, going, to, be,...
3472                 0  ['By, Edward, Wong',, 'WASHINGTON, —, A, top, ...
3473                 0  ['Times, Insider',, 'By, Amisha, Padnani',, 'T...

[3474 rows x 2 columns]

In [14]:
#vectorize_type_material(type_text_df)

In [15]:
#turn type_text_df.ser into list

corpus = list(type_text_df.text)

In [16]:
type(corpus)

list

In [17]:
%time
type(corpus)

CPU times: user 2 µs, sys: 0 ns, total: 2 µs
Wall time: 8.82 µs


list

In [18]:
vectorizer = TfidfVectorizer(stop_words='english')
X = vectorizer.fit_transform(corpus)
# feature_names_tdidf = tdidf_vectorizer.get_feature_names()
# print(len(feature_names_tdidf))
# print(feature_names_tdidf)
# X.toarray()

In [19]:
# type(X[0])

# [Naive Bayes:](https://scikit-learn.org/stable/modules/naive_bayes.html#out-of-core-naive-bayes-model-fitting)

In [20]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB

In [21]:
X = type_text_df.text.apply(lambda x: str(x))
y = type_text_df.type_of_material

In [22]:
type(X[0])

str

# Model 0 
- accuracy = .89
- test_size = .33

In [23]:
vectorizer = TfidfVectorizer(strip_accents='ascii', stop_words='english')

In [24]:
vectorizer

TfidfVectorizer(stop_words='english', strip_accents='ascii')

In [25]:
X = vectorizer.fit_transform(X)

In [26]:
vectorizer

TfidfVectorizer(stop_words='english', strip_accents='ascii')

In [27]:
vectorizer.get_stop_words();

In [28]:
vectorizer.token_pattern;

In [29]:
vectorizer.vocabulary_;

In [30]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [31]:
clf = MultinomialNB()
clf.fit(X_train, y_train)

MultinomialNB()

In [32]:
clf.class_count_

array([2111.,  216.])

In [33]:
y_pred = clf.predict(X_test)

In [34]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [35]:
y

0       1
1       1
2       1
3       1
4       1
       ..
3469    0
3470    0
3471    0
3472    0
3473    0
Name: type_of_material, Length: 3474, dtype: int64

.score is 

In [36]:
y_test

3001    0
1681    0
812     0
2864    0
229     1
       ..
1765    0
1233    0
237     1
1151    0
2971    0
Name: type_of_material, Length: 1147, dtype: int64

In [37]:
clf.score(X_test, y_test)

0.8918918918918919

In [38]:
# sklearn.metrics.confusion_matrix(y_true, 
#                                  y_pred, 
#                                  *, 
#                                  labels=None, 
#                                  sample_weight=None, 
#                                  normalize=None)

In [39]:
y.shape

(3474,)

In [40]:
y_pred.shape

(1147,)

In [42]:
y_test.shape

(1147,)

In [43]:
y_train.shape

(2327,)

In [44]:
confusion_matrix(y_true = y_test, y_pred = y_pred)

array([[1023,    0],
       [ 124,    0]])

In [45]:
tn, fp, fn, tp = confusion_matrix(y_true = y_test, y_pred = y_pred).ravel()
(tn, fp, fn, tp)

(1023, 0, 124, 0)

### predicted all 'news'

# notes from article (https://machinelearningmastery.com/tactics-to-combat-imbalanced-classes-in-your-machine-learning-dataset/)

1. collect more data
2. try changing performace matric
    - confusion matrix: A breakdown of predictions into a table showing correct predictions (the diagonal) and the types of incorrect predictions made (what classes incorrect predictions were assigned).
    
    - precision: A measure of a classifiers exactness.
    
    - recall: A measure of a classifiers completeness
    
    - F1 Score (or F-score): A weighted average of precision and recall.


    * Kappa (or [Cohen’s kappa](https://en.wikipedia.org/wiki/Cohen%27s_kappa)): Classification accuracy normalized by the imbalance of the classes in the data.
    
    * ROC Curves: Like precision and recall, accuracy is divided into sensitivity and specificity and models can be chosen based on the balance thresholds of these values.
    
3. resample data

    - Consider testing under-sampling when you have an a lot data (tens- or hundreds of thousands of instances or more)
    - Consider testing over-sampling when you don’t have a lot of data (tens of thousands of records or less)
    - Consider testing random and non-random (e.g. stratified) sampling schemes.
    - Consider testing different resampled ratios (e.g. you don’t have to target a 1:1 ratio in a binary classification problem, try other ratios)
    
    
4. Try generating synthetic samples
    
    - #### ?? You could sample them empirically within your dataset or you could use a method like Naive Bayes that can sample each attribute independently when run in reverse. **You will have more and different data, but the non-linear relationships between the attributes may not be preserved.** ??

5. Try differente algorithms
    - decision trees often perform well on imbalanced datasets. 
    - C4.5, C5.0, CART and Random Forest
    - [For some example R code using decision trees, see my post titled](http://machinelearningmastery.com/non-linear-classification-in-r-with-decision-trees/)
    - [For an example of using CART in Python and scikit-learn](http://machinelearningmastery.com/get-your-hands-dirty-with-scikit-learn-now/)
    
6. Try penalized models
7. Try a Different Perspective
8. Try getting creative