In [22]:
import pandas as pd

In [63]:
import numpy as np

In [23]:
jan19df = pd.read_csv('jan19.csv', index_col='Unnamed: 0')

In [24]:
jan19df.columns

Index(['abstract', 'web_url', 'snippet', 'lead_paragraph', 'source',
       'multimedia', 'headline', 'keywords', 'pub_date', 'document_type',
       'news_desk', 'section_name', 'byline', 'type_of_material', '_id',
       'word_count', 'uri', 'print_section', 'print_page', 'subsection_name',
       'text'],
      dtype='object')

# <span style="color:red">convert string to datetime objects</span>.



In [35]:
jan19df.pub_date.unique()

array(['2019-01-01T00:00:03+0000', '2019-01-01T00:00:07+0000',
       '2019-01-01T00:15:31+0000', ..., '2019-01-31T23:41:47+0000',
       '2019-01-31T23:47:23+0000', '2019-01-31T23:57:57+0000'],
      dtype=object)

In [36]:
type(jan19df.pub_date[0])

str

In [43]:
(jan19df.word_count.unique()).shape

(1545,)

In [51]:
jan19df.print_section.unique().shape

(16,)

In [52]:
jan19df.print_section.unique()

array([nan, 'A', 'SR', 'B', 'C', 'D', 'BR', 'TR', 'BU', 'RE', 'ST', 'AR',
       'MM', 'SP', 'MB', 'F'], dtype=object)

# <span style="color:red">which page is an article on? can i predict which page a story is from?</span>.

In [53]:
jan19df.print_page.unique().shape

(42,)

In [74]:
pages_used = np.sort(jan19df.print_page.unique())

In [75]:
pages_used

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 30., 31., 32., 34., 35., 38., 42., 43., 44., 46., 54.,
       58., 66., nan])

In [77]:
jan19df.subsection_name.unique()

array([nan, 'Sunday Review', 'Opinion | Business & Economics',
       'Personal Tech', 'Opinion | The World', 'Columnists',
       'Middle East', 'Europe', 'Asia Pacific', 'Self-Care', 'Politics',
       'Move', 'Book Review', 'Media', 'Americas', 'Weddings',
       'Television', 'Commercial Real Estate', 'Dance', 'DealBook',
       'The Daily', 'College Football', 'Eat', 'Art & Design', 'Live',
       'Australia', 'Mind', 'Music', 'Golf', 'Family', 'Economy',
       'Baseball', 'Africa', 'Energy & Environment ', 'Pro Basketball',
       'Lesson Plans', 'Wine, Beer & Cocktails', 'Soccer', 'Canada',
       'Tennis', 'Wirecutter', 'Hockey', 'Pro Football', 'Mutual Funds',
       'Olympics', 'Learning'], dtype=object)

In [80]:
news = jan19df[jan19df['type_of_material'] == 'News']

In [81]:
oped = jan19df[jan19df['type_of_material'] == 'Op-Ed']

In [82]:
jan19df.type_of_material.unique()

array(['Op-Ed', 'News'], dtype=object)

In [86]:
news.subsection_name.unique()

array([nan, 'Middle East', 'Europe', 'Asia Pacific', 'Self-Care',
       'Politics', 'Move', 'Book Review', 'Media', 'Americas', 'Weddings',
       'Television', 'Commercial Real Estate', 'Dance', 'DealBook',
       'The Daily', 'College Football', 'Eat', 'Personal Tech',
       'Art & Design', 'Live', 'Australia', 'Mind', 'Music', 'Golf',
       'Family', 'Economy', 'Baseball', 'Africa', 'Energy & Environment ',
       'Pro Basketball', 'Lesson Plans', 'Wine, Beer & Cocktails',
       'Soccer', 'Canada', 'Tennis', 'Wirecutter', 'Hockey',
       'Pro Football', 'Mutual Funds', 'Olympics', 'Learning'],
      dtype=object)

In [84]:
oped.subsection_name.unique()

array([nan, 'Sunday Review', 'Opinion | Business & Economics',
       'Personal Tech', 'Opinion | The World', 'Columnists'], dtype=object)

In [ ]:
103

You can use boolean indexing:

df = pd.DataFrame({'Sales':[10,20,30,40,50], 'A':[3,4,7,6,1]})
print (df)
   A  Sales
0  3     10
1  4     20
2  7     30
3  6     40
4  1     50

s = 30

df1 = df[df['Sales'] >= s]
print (df1)
   A  Sales
2  7     30
3  6     40
4  1     50

df2 = df[df['Sales'] < s]
print (df2)
   A  Sales
0  3     10
1  4     20
It's also possible to invert mask by ~:

mask = df['Sales'] >= s
df1 = df[mask]
df2 = df[~mask]
print (df1)
   A  Sales
2  7     30
3  6     40
4  1     50

print (df2)
   A  Sales
0  3     10
1  4     20
print (mask)
0    False
1    False
2     True
3     True
4     True
Name: Sales, dtype: bool

print (~mask)
0     True
1     True
2    False
3    False
4    False
Name: Sales, dtype: bool